apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argowf.yaml

patches:
- path: patch-deployment-argo-server.yaml
  target:
    kind: Deployment
    name: argo-server
- path: patch-deployment-workflow-controller.yaml
  target:
    kind: Deployment
    name: workflow-controller
- path: patch-configmap-workflow-controller-configmap.yaml
  target:
    kind: ConfigMap
    name: workflow-controller-configmap
