apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argowf.yaml

patches:
- path: patch-deployment-image-argocli.yaml
  target:
    kind: Deployment
    name: argo-server
- path: patch-deployment-image-workflow-controller.yaml
  target:
    kind: Deployment
    name: workflow-controller
