apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../upstream

resources:
  - namespace.yaml

images:
  - name: quay.io/argoproj/workflow-controller
    newTag: v3.2.3
  - name: quay.io/argoproj/argocli
    newTag: v3.2.3

patches:
- path: patch-deployment-workflow-controller.yaml
  target:
    kind: Deployment
    name: workflow-controller
- path: patch-configmap-workflow-controller-configmap.yaml
  target:
    kind: ConfigMap
    name: workflow-controller-configmap
