apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../upstream

resources:
  - namespace.yaml

patches:
- path: patch-configmap-workflow-controller-configmap.yaml
  target:
    kind: ConfigMap
    name: workflow-controller-configmap
